- name: Run jenkins container
  hosts: jenkins
  tasks:

    - name: Pull Jenkins image
      docker_image:
        name: jenkins/jenkins
        source: pull

    - name: Create Jenkins container
      docker_container:
        name: myjenkins
        image: jenkins/jenkins
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes: "jenkins_home:/var/jenkins_home"
        state: started
